pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'make -C calnex clean all'
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: '**/build/*.tar', fingerprint: false
            }
        }
    }
}