pipeline {
    agent any

    stages {
        stage('Code') {
            steps {
                // Get some code from a GitHub repository
                git branch: 'cx', url: 'git@github.com:Calnex/sen-noVNC'
            }

        }
        
        stage('Build') {
            steps {
                sh 'make -C calnex clean all'
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: '**/build/*.tar', fingerprint: false
            }
        }

        stage('Release') {
            steps {
                fileOperations([
                    fileCopyOperation(
                        includes: '**/build/*.tar',
                        targetLocation: '/mnt/releases/',
                        flattenFiles: true
                        )
                    ])
                
            }
        }
    }
}
