pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'make -C calnex clean all'
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: '**/build/*.tar', fingerprint: false
            }
        }

        stage('Release')
        {
            steps {
                // folllowing structure:
                // dir1/info-app.txt
                // dir1/error-app.txt
                fileOperations([fileCopyOperation(
                    includes: '**/build/*.tar',
                    targetLocation: '/mnt/releases',
                    flattenFiles: true
                ])            
            }
        }
    }
}